version: '3'
services:
  postgres:
    image: postgres # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - 8001:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  app:
    image: node
    depends_on: 
      - postgres
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8002:3000
    command: >
      bash -c "cd /usr/src/app
      && npm run watch"
    links:
      - postgres